### PR TITLE
Add compatibility for php8

### PR DESCRIPTION
**Pull request by ferrastas**
As described in
https://github.com/php/php-src/blob/PHP-8.0.0/UPGRADING.INTERNALS several things
regarding TSRM has been removed.

### CODE REVIEW

**Comment by ferrastas** [comment]
Hey @hthetiot, will you have some time to review and check if worth to be merged? Thanks :D

**Comment by hthetiot** [comment]
@ferrastas Did you test it ?

**Comment by hthetiot** [comment]
Does it break PHP 7 support @ferrastas  ?

**Comment by ferrastas** [comment]
> Does it break PHP 7 support @ferrastas ?

It shouldn't, but to make sure let me create a quick test

**Comment by hthetiot** [comment]
@ferrastas let me know if php7 is ok and i will merge

**Comment by ferrastas** [comment]
Sorry for my late response. I tried to set a GitHub Action to test it but I've limited knowledge :/
What I did instead is to set a Docker image to do a small test using `master` with `php:7.4` and `php:8.0` and this PR against the same PHP versions. Here you have it: https://github.com/ferrastas/test-php-stemmer

**Comment by ferrastas** [comment]
For the record, this is the output if my tests:


## PHP 7.x - Using php-stemmer master
```
$ docker build --build-arg PHP_VERSION=7.4 --tag test:7.4 .
...
$ docker run -t test:7.4 && echo $?
dakpann
balletj
0
```

## PHP 8.x - Using php-stemmer master
```
$ docker build --build-arg PHP_VERSION=8.0 --tag test:8.0 .
...
#6 17.28 /tmp/php-stemmer-master/stemmer.c: In function 'zif_stemword':
#6 17.28 /tmp/php-stemmer-master/stemmer.c:87:47: error: expected ')' before 'TSRMLS_CC'
#6 17.28      if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "zzz", &arg,&lang,&enc) == FAILURE)RETURN_NULL();
#6 17.28                                                ^~~~~~~~~
#6 17.28 /tmp/php-stemmer-master/stemmer.c:87:9: error: too few arguments to function 'zend_parse_parameters'
#6 17.28      if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "zzz", &arg,&lang,&enc) == FAILURE)RETURN_NULL();
#6 17.28          ^~~~~~~~~~~~~~~~~~~~~
#6 17.28 In file included from /usr/local/include/php/main/php.h:35,
#6 17.28                  from /tmp/php-stemmer-master/stemmer.c:5:
#6 17.28 /usr/local/include/php/Zend/zend_API.h:304:22: note: declared here
#6 17.28  ZEND_API zend_result zend_parse_parameters(uint32_t num_args, const char *type_spec, ...);
#6 17.28                       ^~~~~~~~~~~~~~~~~~~~~
#6 17.30 make: *** [Makefile:209: stemmer.lo] Error 1
```

## PHP 7.x - Using php-stemmer php-8 branch
```
$ docker build --build-arg PHP_STEMMER_VERSION=php-8 --build-arg PHP_VERSION=7.4 --tag test-pr:7.4 .
...
$ docker run -t test-pr:7.4 && echo $?
dakpann
balletj
0
```

## PHP 8.x - Using php-stemmer php-8 branch
```
$ docker build --build-arg PHP_STEMMER_VERSION=php-8 --build-arg PHP_VERSION=8.0 --tag test-pr:8.0 .
...
$ docker run -t test-pr:8.0 && echo $?
dakpann
balletj
0
```

**Comment by hthetiot** [comment]
> Sorry for my late response. 

No problem, thank you for testing.

**Comment by hthetiot** [comment]
It's merged, thank you for contributing.;
Let me know if you want to get more right on the repository, im not actively maintaining this project anymore.

**Pull request merged**
